"""Crear tablas iniciales

Revision ID: cb1236790615
Revises: 
Create Date: 2026-10-02 18:08:32.224814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1236790615'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_table('comunicado',
    sa.Column('id_comunicado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('publicado_por', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['publicado_por'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comunicado')
    )
    op.create_table('mensaje_directo',
    sa.Column('id_mensaje_directo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha_leido', sa.DateTime(), nullable=True),
    sa.Column('emisor_id', sa.Integer(), nullable=False),
    sa.Column('receptor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emisor_id'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensaje_directo')
    )
    op.create_table('notificacion',
    sa.Column('id_notificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('enlace', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('perfil',
    sa.Column('id_perfil', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_perfil'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('recordatorio',
    sa.Column('id_recordatorio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_recordatorio')
    )
    op.create_table('relacion_usuario',
    sa.Column('id_relacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('relacionado_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relacionado_id'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_relacion')
    )
    op.create_table('servidor',
    sa.Column('id_servidor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_servidor')
    )
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['padre_id'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id_servidor'], ),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('comunicado_visto',
    sa.Column('id_comunicado_visto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comunicado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_visto', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comunicado_id'], ['comunicado.id_comunicado'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comunicado_visto')
    )
    op.create_table('miembro_servidor',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_union', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id_servidor'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'servidor_id')
    )
    op.create_table('usuario_rol',
    sa.Column('id_usuario_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('asignado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id_rol'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id_servidor'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario_rol')
    )
    op.create_table('canal',
    sa.Column('id_canal', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['creador_id'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id_servidor'], ),
    sa.PrimaryKeyConstraint('id_canal')
    )
    op.create_table('comunicado_destinatario',
    sa.Column('id_comunicado_destinatario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comunicado_id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=True),
    sa.Column('canal_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['canal_id'], ['canal.id_canal'], ),
    sa.ForeignKeyConstraint(['comunicado_id'], ['comunicado.id_comunicado'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id_servidor'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comunicado_destinatario')
    )
    op.create_table('mensaje',
    sa.Column('id_mensaje', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('editado', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canal.id_canal'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('miembro_canal',
    sa.Column('id_miembro_canal', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=False),
    sa.Column('fecha_union', sa.DateTime(), nullable=True),
    sa.Column('rol_en_canal', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canal.id_canal'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_miembro_canal')
    )
    op.create_table('mensaje_visto',
    sa.Column('id_mensaje_visto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mensaje_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_visto', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mensaje_id'], ['mensaje.id_mensaje'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensaje_visto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensaje_visto')
    op.drop_table('miembro_canal')
    op.drop_table('mensaje')
    op.drop_table('comunicado_destinatario')
    op.drop_table('canal')
    op.drop_table('usuario_rol')
    op.drop_table('miembro_servidor')
    op.drop_table('comunicado_visto')
    op.drop_table('categoria')
    op.drop_table('servidor')
    op.drop_table('relacion_usuario')
    op.drop_table('recordatorio')
    op.drop_table('perfil')
    op.drop_table('notificacion')
    op.drop_table('mensaje_directo')
    op.drop_table('comunicado')
    op.drop_table('usuario')
    op.drop_table('rol')
    # ### end Alembic commands ###
